/* =============================================================================
 * weoc-map.js  —  ArcGIS map factory for WebEOC v2.0 boards
 * -----------------------------------------------------------------------------
 * One implementation for every map across Event Reporting, Task Management,
 * Facilities Management (and any future board). Replaces the ~150 lines of
 * inline `require([...])` + control wiring that each Display/Details/Input view
 * had copy-pasted (and drifted apart on).
 *
 * Design rules:
 *   - ZERO hardcoded element IDs. Everything is scoped to a root element, so any
 *     number of maps can live on one page (the reason the old views had to
 *     prefix ids viewDiv / detViewDiv / locViewDiv).
 *   - Declarative-first: a correctly-marked-up container renders out of the box
 *     on DOM ready via auto-init. No per-view JS needed for the 80% case.
 *   - Hooks/registries for the per-board 20% (Event canvas badges, popover field
 *     sets, colour palettes, the OpenView details target).
 *
 * Dependencies: ArcGIS JS API 4.29 (`require`), loaded before this file.
 *               jQuery is NOT required by the core (only used if a board wants).
 *
 * Public API:
 *   WeocMap.create(rootEl|selector, opts)   -> instance      (programmatic)
 *   WeocMap.autoInit(scope)                 -> instance[]     (scans [data-wui-map])
 *   WeocMap.registerStyle(name, fn)         -> register a marker-symbol builder
 *   WeocMap.registerPalette(name, map)      -> register a field->colour map
 *   WeocMap.BASEMAPS                         -> canonical basemap registry
 *
 * Instance API:
 *   .view            ArcGIS MapView (null until ready)
 *   .layer           the GraphicsLayer markers live on
 *   .ready(fn)       run fn once the view is ready (or now, if already)
 *   .refresh()       re-read the data source and re-plot (display/input)
 *   .setMarker(lat,lon)   place/replace the single marker (details/input)
 *   .focus(lat,lon,zoom)  animate to a point
 *   .resize()        force the view to re-measure (after layout/visibility change)
 *   .destroy()       tear down view + listeners
 *
 * Optional companion widgets (opts, not markup — unlike the popover/controls,
 * these two are generated by the factory, not hand-authored per board):
 *   opts.weather = { city, cityKey, temp, unit, condition, conditionKey,
 *                    humidity, wind, visibility, icon }  -> `.wui-map-weather`
 *   opts.legend  = true | [{ cls, key, fallback }, ...]  -> `.wui-map-legend`
 *   Both no-op when omitted. `data-map-legend="true"` also enables the
 *   default 4-tier legend declaratively.
 * ========================================================================== */

(function (global) {
  "use strict";

  /* ---------------------------------------------------------------------------
   * Canonical config — single source of truth (kills the 4.28/4.29 &
   * streets-vector/streets-navigation-vector/gray-vector drift between views).
   * ------------------------------------------------------------------------ */

  // Ordered so data-basemap-index="0..3" keeps working with existing markup.
  // Each basemap resolves to a light or dark ArcGIS id by the active theme.
  // streets + gray have true dark variants; hybrid (imagery) and topo have none,
  // so they fall back to their light id in both themes.
  var BASEMAPS = [
    { key: "streets", label: "Streets",     light: "streets-navigation-vector", dark: "streets-night-vector" },
    { key: "hybrid",  label: "Hybrid",      light: "hybrid",                    dark: "hybrid"              },
    { key: "topo",    label: "Topographic", light: "topo-vector",               dark: "topo-vector"         },
    { key: "gray",    label: "Gray",        light: "gray",                      dark: "dark-gray"           }
  ];
  // gray/dark-gray use the classic (non "-vector") canvas ids — the "-vector"
  // variants (gray-vector/dark-gray-vector) were retired in this ArcGIS build and
  // render blank; the original inline map used "dark-gray", which still loads.
  // topo has no dark basemap here, so it stays light in both themes.
  var BASEMAP_DEFAULT = 3; // gray — renders gray-vector (light) / dark-gray-vector (dark)

  // Resolve a basemap entry to the ArcGIS id matching the current theme.
  function themedBasemapId(idx) {
    var b = BASEMAPS[idx] || BASEMAPS[BASEMAP_DEFAULT];
    return isDark() ? (b.dark || b.light) : b.light;
  }

  var DEFAULT_CENTER = [54.0, 24.0]; // [lon, lat] — UAE
  var DEFAULT_ZOOM   = 7;

  var ESRI_MODULES = [
    "esri/Map",
    "esri/views/MapView",
    "esri/Graphic",
    "esri/layers/GraphicsLayer"
  ];

  /* ---------------------------------------------------------------------------
   * Registries
   * ------------------------------------------------------------------------ */

  // Marker-symbol builders. A builder receives (attrs, ctx) and returns either an
  // ArcGIS symbol object, or a Promise resolving to one (e.g. the canvas badge).
  // attrs = the point's data; ctx = { instance, palette, color, theme }.
  var STYLES = {};

  // Named field->colour maps, e.g. { Operational:[25,135,84], Closed:[220,53,69] }.
  var PALETTES = {};

  /* ---------------------------------------------------------------------------
   * Small DOM / parse helpers (vanilla — no jQuery dependency)
   * ------------------------------------------------------------------------ */

  function el(scope, selector) {
    if (!selector) return null;
    return (scope || document).querySelector(selector);
  }
  function els(scope, selector) {
    return Array.prototype.slice.call((scope || document).querySelectorAll(selector));
  }
  function isDark() {
    var t = document.documentElement.getAttribute("data-theme") ||
            document.body.getAttribute("data-theme");
    return t === "dark";
  }
  function num(v) {
    var n = parseFloat(v);
    return isNaN(n) ? null : n;
  }
  function parseColor(str, fallback) {
    // "r,g,b" or "r,g,b,a" -> [..]; else fallback
    if (!str) return fallback || null;
    var parts = String(str).split(",").map(function (s) { return parseFloat(s.trim()); });
    if (parts.some(isNaN) || parts.length < 3) return fallback || null;
    if (parts.length === 3) parts.push(1);
    return parts;
  }
  function parseCenter(str) {
    if (!str) return null;
    var p = String(str).split(",").map(function (s) { return parseFloat(s.trim()); });
    if (p.length < 2 || isNaN(p[0]) || isNaN(p[1])) return null;
    return [p[0], p[1]];
  }
  // Collect ALL data-* on a node into a plain object: data-record-number -> recordNumber.
  function dataset(node) {
    var out = {};
    if (node && node.dataset) {
      for (var k in node.dataset) { if (Object.prototype.hasOwnProperty.call(node.dataset, k)) out[k] = node.dataset[k]; }
    }
    return out;
  }
  function resolveBasemapStart(root) {
    // explicit data-map-basemap (by key) wins; else the default (theme picks variant).
    var want = root.getAttribute("data-map-basemap");
    if (want) {
      for (var i = 0; i < BASEMAPS.length; i++) {
        if (BASEMAPS[i].key === want) return i;
      }
    }
    return BASEMAP_DEFAULT;
  }

  /* ---------------------------------------------------------------------------
   * Built-in marker styles
   * ------------------------------------------------------------------------ */

  // "pin" — single fixed-colour simple-marker (Details, Input).
  STYLES.pin = function (attrs, ctx) {
    var c = ctx.color || [24, 95, 165, 1];
    var outline = ctx.outline || [c[0] * 0.7 | 0, c[1] * 0.7 | 0, c[2] * 0.7 | 0, 1];
    return {
      type: "simple-marker",
      style: "circle",
      color: c,
      outline: { color: outline, width: 2 },
      size: ctx.size || "14px"
    };
  };

  // "dot" — colour driven by a field via a palette (Tasks by priority, Facilities
  //   by status). ctx.palette is the resolved {value:[r,g,b]} map; colorField the key.
  STYLES.dot = function (attrs, ctx) {
    var key = attrs[ctx.colorField];
    var c = (ctx.palette && ctx.palette[key]) || ctx.color || [100, 100, 100];
    if (c.length === 3) c = c.concat(1);
    return {
      type: "simple-marker",
      style: "circle",
      color: c,
      outline: { color: [255, 255, 255, 1], width: 1.5 },
      size: ctx.size || "12px"
    };
  };

  // "badge" — canvas-composited picture-marker: tinted circle + classification
  //   icon + tier ring (Event Reporting). Configurable, async (returns Promise).
  //   ctx.iconBase: URL prefix; ctx.iconSet: {classificationKey: filename};
  //   ctx.tierField / ctx.iconField name the attributes; CSS vars --tier-N-*.
  STYLES.badge = function (attrs, ctx) {
    var tier = parseInt(String(attrs[ctx.tierField || "severity"] || "").replace(/\D/g, ""), 10) || 1;
    var iconUrl = badgeIconUrl(attrs[ctx.iconField || "classification"], ctx);
    return buildBadgeUrl(iconUrl, tier).then(function (url) {
      return { type: "picture-marker", url: url, width: "40px", height: "40px" };
    });
  };

  function badgeIconUrl(classification, ctx) {
    var key = String(classification || "").toLowerCase().trim().replace(/\s+/g, "-");
    var base = ctx.iconBase || "";
    var set = ctx.iconSet || {};
    if (set[key]) return base + set[key];
    return base + (ctx.iconFallback || "location.svg");
  }

  function cssVar(name) {
    return getComputedStyle(document.documentElement).getPropertyValue(name).trim();
  }

  function buildBadgeUrl(iconUrl, tier) {
    return new Promise(function (resolve) {
      var t = (tier >= 1 && tier <= 4) ? tier : 1;
      var fill   = cssVar("--tier-" + t + "-muted") || "rgba(106,177,67,0.15)";
      var stroke = cssVar("--tier-" + t + "-color") || "#6ab143";
      var dpr  = global.devicePixelRatio || 2;
      var size = 40 * dpr, r = size / 2;
      var cvs  = document.createElement("canvas");
      cvs.width = cvs.height = size;
      var ctx2d = cvs.getContext("2d");

      ctx2d.beginPath();
      ctx2d.arc(r, r, r - 2, 0, Math.PI * 2);
      ctx2d.fillStyle = fill;
      ctx2d.fill();

      var img = new Image();
      img.crossOrigin = "anonymous";
      img.onload = function () {
        try {
          var iconSize = Math.round(size * 0.55);
          var pad = (size - iconSize) / 2;
          ctx2d.drawImage(img, pad, pad, iconSize, iconSize);
          ctx2d.beginPath();
          ctx2d.arc(r, r, r - 2, 0, Math.PI * 2);
          ctx2d.strokeStyle = stroke;
          ctx2d.lineWidth = 1.5 * dpr;
          ctx2d.stroke();
          resolve(cvs.toDataURL("image/png"));
        } catch (e) { resolve(iconUrl); }
      };
      img.onerror = function () { resolve(iconUrl); };
      img.src = iconUrl;
    });
  }

  /* ---------------------------------------------------------------------------
   * Instance
   * ------------------------------------------------------------------------ */

  function WeocMapInstance(root, opts) {
    this.root = root;
    this.opts = opts;
    this.view = null;
    this.map = null;
    this.layer = null;
    this._readyCbs = [];
    this._isReady = false;
    this._handlers = [];           // {target, type, fn} for teardown
    this._basemapIndex = opts.basemapIndex;
    this._viewDiv = opts.viewDiv;  // the inner .wui-map-view element

    this._resizeHandle = null;
    if (global.WUI && global.WUI.responsive) {
      var self0 = this;
      this._resizeHandle = global.WUI.responsive.observe(this._viewDiv, function (info) {
        if (info.tooSmall) { return; }
        self0.resize();
      }, { minWidth: 40, minHeight: 40 });
    }

    this._init();
    this._renderWeather();
    this._renderLegend();
  }

  WeocMapInstance.prototype._on = function (target, type, fn, capture) {
    target.addEventListener(type, fn, !!capture);
    this._handlers.push({ target: target, type: type, fn: fn, capture: !!capture });
  };

  WeocMapInstance.prototype.ready = function (fn) {
    if (this._isReady) fn(this);
    else this._readyCbs.push(fn);
    return this;
  };

  WeocMapInstance.prototype._init = function () {
    var self = this;
    if (typeof global.require === "undefined") {
      console.warn("[WeocMap] ArcGIS `require` not found — is js.arcgis.com loaded before weoc-map.js?");
      return;
    }
    var o = this.opts;

    global.require(ESRI_MODULES, function (Map, MapView, Graphic, GraphicsLayer) {
      self._Graphic = Graphic;
      self.layer = new GraphicsLayer({ id: "weoc-marker-layer" });

      self.map = new Map({
        basemap: themedBasemapId(self._basemapIndex),
        layers: [self.layer]
      });

      // Details mode can start centred on the record if it has coords.
      var startCenter = o.center, startZoom = o.zoom;
      if (o.mode === "details" && o.lat != null && o.lon != null) {
        startCenter = [o.lon, o.lat];
        startZoom = o.focusZoom;
      }

      self.view = new MapView({
        container: self._viewDiv,
        map: self.map,
        center: startCenter,
        zoom: startZoom,
        ui: { components: [] }
      });
      self.view.popupEnabled = false;

      self.view.when(function () {
        self._isReady = true;
        self._wireControls();
        MODES[o.mode].onReady(self);
        self._readyCbs.forEach(function (cb) { cb(self); });
        self._readyCbs = [];
      });
    });
  };

  // Build one marker Graphic from a point object {lat, lon, ...attrs}.
  // Handles sync OR async (Promise) style builders uniformly.
  WeocMapInstance.prototype._makeGraphic = function (pt) {
    var self = this, o = this.opts;
    var ctx = {
      instance: self, theme: isDark() ? "dark" : "light",
      color: o.color, outline: o.outline, size: o.size,
      colorField: o.colorField, palette: o.palette,
      tierField: o.tierField, iconField: o.iconField,
      iconBase: o.iconBase, iconSet: o.iconSet, iconFallback: o.iconFallback
    };
    var geometry = { type: "point", longitude: pt.lon, latitude: pt.lat };
    var make = function (sym) {
      return sym ? new self._Graphic({ geometry: geometry, symbol: sym, attributes: pt }) : null;
    };
    // A throwing style builder must never propagate out of a map-click handler
    // (it would wedge the ArcGIS view) — log and skip the marker instead.
    var symbol;
    try { symbol = o.style(pt, ctx); }
    catch (e) { console.warn("[WeocMap] style builder threw:", e); return Promise.resolve(null); }
    return (symbol && typeof symbol.then === "function")
      ? symbol.then(make).catch(function () { return null; })
      : Promise.resolve(make(symbol));
  };

  WeocMapInstance.prototype._plot = function (points) {
    var self = this;
    if (!self.layer) return;
    self.layer.removeAll();
    Promise.all(points.map(function (p) { return self._makeGraphic(p); }))
      .then(function (graphics) {
        var valid = graphics.filter(Boolean);
        valid.forEach(function (g) { self.layer.add(g); });
        if (self.opts.fit && valid.length) {
          self.view.goTo(self.layer.graphics, { padding: 60, duration: 600 }).catch(function () {});
        }
      });
  };

  WeocMapInstance.prototype.setMarker = function (lat, lon, extraAttrs) {
    var self = this;
    if (lat == null || lon == null) { if (self.layer) self.layer.removeAll(); return; }
    var pt = Object.assign({ lat: lat, lon: lon }, extraAttrs || {});
    self._plot([pt]);
  };

  WeocMapInstance.prototype.focus = function (lat, lon, zoom) {
    if (!this.view) return;
    this.view.goTo({ center: [lon, lat], zoom: zoom || this.opts.focusZoom },
                   { duration: 500, easing: "ease-in-out" }).catch(function () {});
  };

  // Pan to a plotted marker by its id and open its popover (display mode).
  // The list-view "locate" button pattern, shared by Event / Task / Facility.
  WeocMapInstance.prototype.locate = function (id, zoom) {
    var self = this;
    if (!self.view || !self.layer) return self;
    var g = self.layer.graphics.find(function (x) {
      return x.attributes && x.attributes.id == id; // == : data-id may be string vs number
    });
    if (!g) return self;
    self.view.goTo(
      { center: [g.attributes.lon, g.attributes.lat], zoom: zoom || self.opts.focusZoom },
      { duration: 600, easing: "ease-in-out" }
    ).then(function () {
      if (!self._popover) return;
      var pos = anchorXY(self, g);
      self._popover.show(g.attributes, pos.x, pos.y);
    }).catch(function () {});
    return self;
  };

  WeocMapInstance.prototype.refresh = function () {
    if (this._isReady && MODES[this.opts.mode].refresh) MODES[this.opts.mode].refresh(this);
    return this;
  };

  WeocMapInstance.prototype.resize = function () {
    if (this.view && this.view.resize) this.view.resize();
    return this;
  };

  // Re-resolve the current basemap for the active theme (call on theme change).
  WeocMapInstance.prototype.syncTheme = function () {
    if (this.view && this.view.map) this.view.map.basemap = themedBasemapId(this._basemapIndex);
    return this;
  };

  WeocMapInstance.prototype.destroy = function () {
    if (this._resizeHandle) { this._resizeHandle.disconnect(); this._resizeHandle = null; }
    this._handlers.forEach(function (h) { h.target.removeEventListener(h.type, h.fn, h.capture); });
    this._handlers = [];
    if (this.view) { this.view.destroy(); this.view = null; }
  };

  /* ---------------------------------------------------------------------------
   * Shared control overlay wiring — scoped to root via [data-map-ctrl].
   * Replaces the per-view id-prefixed handlers (basemapToggleBtn /
   * detBasemapToggleBtn / locBasemapToggleBtn ...).
   * ------------------------------------------------------------------------ */

  WeocMapInstance.prototype._wireControls = function () {
    var self = this, root = this.root, view = this.view;

    function ctrl(name) { return el(root, '[data-map-ctrl="' + name + '"]'); }
    function bind(name, fn) {
      var node = ctrl(name);
      if (node) self._on(node, "click", function (e) { e.preventDefault(); fn(e, node); });
    }

    // Basemap tools toggle
    var toggle = ctrl("basemap-toggle");
    var tools  = el(root, '[data-map-basemap-tools]');
    if (toggle && tools) {
      self._on(toggle, "click", function (e) {
        e.preventDefault();
        tools.classList.toggle("open");
        toggle.classList.toggle("active", tools.classList.contains("open"));
      });
    }
    // Individual basemap buttons (data-basemap-index or data-basemap key)
    els(root, "[data-basemap-index],[data-basemap]").forEach(function (btn) {
      self._on(btn, "click", function (e) {
        e.preventDefault();
        var idx = btn.hasAttribute("data-basemap-index")
          ? parseInt(btn.getAttribute("data-basemap-index"), 10)
          : BASEMAPS.findIndex(function (b) { return b.key === btn.getAttribute("data-basemap"); });
        if (isNaN(idx) || !BASEMAPS[idx]) return;
        self._basemapIndex = idx;
        view.map.basemap = themedBasemapId(idx);
        els(root, "[data-basemap-index],[data-basemap]").forEach(function (b) { b.classList.remove("active"); });
        btn.classList.add("active");
        if (tools) tools.classList.remove("open");
        if (toggle) toggle.classList.remove("active");
      });
    });

    bind("zoom-in",  function () { view.goTo({ zoom: view.zoom + 1 }, { animate: true }); });
    bind("zoom-out", function () { view.goTo({ zoom: view.zoom - 1 }, { animate: true }); });
    bind("reset-view", function () {
      view.goTo({ center: self.opts.center, zoom: self.opts.zoom }, { animate: true });
    });
    bind("reset-orientation", function () { view.goTo({ rotation: 0 }, { animate: true }); });
    bind("fullscreen", function (e, node) { self._toggleFullscreen(node); });

    // Click outside the toggle + tools panel closes the basemap tools.
    self._on(document, "click", function (e) {
      if (!tools || !tools.classList.contains("open")) return;
      if (e.target.closest('[data-map-ctrl="basemap-toggle"]')) return; // toggle handles itself
      if (tools.contains(e.target)) return;                             // basemap pick closes via its own handler
      tools.classList.remove("open");
      if (toggle) toggle.classList.remove("active");
    });
  };

  WeocMapInstance.prototype._toggleFullscreen = function (btn) {
    var self = this;
    // The fullscreen class goes on the wrap element (data-map-wrap or the root).
    var wrap = el(this.root, "[data-map-wrap]") || this.root;
    var entering = !wrap.classList.contains("is-fs");
    wrap.classList.toggle("is-fs", entering);
    document.body.classList.toggle("no-scroll", entering);
    var icon = btn && btn.querySelector(".material-symbols-outlined");
    if (icon) icon.textContent = entering ? "fullscreen_exit" : "fullscreen";
    setTimeout(function () { self.resize(); if (self._popover) self._popover.reposition(); }, 50);
  };

  /* ---------------------------------------------------------------------------
   * Optional companion widgets — weather + legend overlays.
   * Unlike the popover/controls (hand-authored markup the factory only wires),
   * these two are generated entirely from opts — a board includes them just by
   * passing opts.weather / opts.legend, no markup to write. Idempotent: reuses
   * an existing [data-map-weather]/[data-map-legend] node if one is already
   * hand-authored inside [data-map-wrap], otherwise creates and appends one.
   * ------------------------------------------------------------------------ */

  var DEFAULT_TIERS = [
    { cls: "tier-1", key: "Tier1", fallback: "Tier 1" },
    { cls: "tier-2", key: "Tier2", fallback: "Tier 2" },
    { cls: "tier-3", key: "Tier3", fallback: "Tier 3" },
    { cls: "tier-4", key: "Tier4", fallback: "Tier 4" }
  ];

  function i18nApply(node) {
    if (global.WUI && global.WUI.i18n && typeof global.WUI.i18n.apply === "function") global.WUI.i18n.apply(node);
  }
  function i18nText(key, fallback) {
    return (global.WUI && global.WUI.i18n && typeof global.WUI.i18n.t === "function") ? global.WUI.i18n.t(key, fallback) : fallback;
  }
  function wrapOf(inst) {
    return el(inst.root, "[data-map-wrap]") || inst.root;
  }
  // Each metric box is a tiny `.wui-plane` (weoc-containers.css) — `.wui-p-1`
  // overrides its default padding down to fit this dense a widget.
  function weatherMetric(icon, key, value) {
    return '<div class="wui-plane wui-p-1 wui-flex wui-flex-col wui-gap-1">' +
      '<div class="wui-flex wui-items-center wui-gap-1 wui-text-2xs wui-text-secondary">' +
      '<span class="material-symbols-outlined wui-text-xs">' + icon + '</span><span data-wui-i18n="' + key + '">' + key + '</span></div>' +
      '<div class="wui-text-xs wui-bold wui-text-primary">' + (value != null ? value : "—") + '</div></div>';
  }

  WeocMapInstance.prototype._renderWeather = function () {
    var cfg = this.opts.weather;
    if (!cfg) return;
    var self = this;
    var host = el(wrapOf(this), "[data-map-weather]");
    if (!host) {
      host = document.createElement("div");
      host.setAttribute("data-map-weather", "true");
      host.className = "map-overlay";
      wrapOf(this).appendChild(host);
    }
    // Icon containers -> wui-icon-bubble, "Live" pill -> wui-chip, metric
    // boxes -> wui-plane (above), all text -> typography utilities. Only
    // .wui-map-weather* here is real layout (weoc-maps.css); everything
    // else is the shared component fleet, per the class's own header comment.
    host.innerHTML =
      '<div class="wui-map-weather">' +
        '<div class="wui-map-weather-hdr">' +
          '<div class="wui-map-weather-location">' +
            '<div class="wui-icon-bubble sm warning"><span class="material-symbols-outlined">location_on</span></div>' +
            '<div>' +
              '<div class="wui-text-2xs wui-bold wui-text-primary" data-wui-i18n="' + (cfg.cityKey || "") + '">' + (cfg.city || "") + '</div>' +
              '<div class="wui-text-2xs wui-text-secondary" data-map-weather-updated="true"></div>' +
            '</div>' +
          '</div>' +
          '<span class="wui-chip wui-chip-xs success"><span class="material-symbols-outlined">verified</span><span data-wui-i18n="Live">Live</span></span>' +
        '</div>' +
        '<div class="wui-map-weather-main">' +
          '<div class="wui-icon-bubble sm warning"><span class="material-symbols-outlined">' + (cfg.icon || "sunny") + '</span></div>' +
          '<div>' +
            '<div class="wui-flex wui-items-end wui-gap-1">' +
              '<span class="wui-text-lg wui-bold wui-text-primary">' + cfg.temp + '</span>' +
              '<span class="wui-text-2xs wui-bold wui-text-secondary">' + (cfg.unit || "°C") + '</span>' +
            '</div>' +
            '<div class="wui-text-xs wui-semibold wui-text-ui" data-wui-i18n="' + (cfg.conditionKey || "") + '">' + (cfg.condition || "") + '</div>' +
          '</div>' +
        '</div>' +
        '<div class="wui-map-weather-metrics">' +
          weatherMetric("water_drop", "Humidity", cfg.humidity) +
          weatherMetric("air", "Wind", cfg.wind) +
          weatherMetric("visibility", "Visibility", cfg.visibility) +
        '</div>' +
      '</div>';
    i18nApply(host);
    this._weatherHost = host;
    this._refreshWeatherTimestamp();
    this._on(document.documentElement, "wui:langchange", function () { self._refreshWeatherTimestamp(); });
  };

  WeocMapInstance.prototype._refreshWeatherTimestamp = function () {
    if (!this._weatherHost) return;
    var node = el(this._weatherHost, "[data-map-weather-updated]");
    if (!node) return;
    var now = new Date();
    var timeText = now.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
    node.textContent = i18nText("UpdatedAt", "Updated {time}").replace("{time}", timeText);
  };

  WeocMapInstance.prototype._renderLegend = function () {
    var cfg = this.opts.legend;
    if (!cfg) return;
    var tiers = Array.isArray(cfg) ? cfg : DEFAULT_TIERS;
    var host = el(wrapOf(this), "[data-map-legend]");
    if (!host) {
      host = document.createElement("div");
      host.setAttribute("data-map-legend", "true");
      host.className = "wui-map-legend";
      wrapOf(this).appendChild(host);
    }
    // Dot is the shared `.wui-status-dot` (weoc-indicators.css) at its `-sm`
    // size, colored via the existing tier-N variant (weoc-tier-colors.css) —
    // not a bespoke legend-only dot.
    // NOTE: these are assigned via .innerHTML, parsed as HTML (not XML) — a
    // self-closing `<span .../>` on a non-void element does NOT close it;
    // everything after would nest inside it instead of sitting as a sibling
    // (which silently collapsed every item into one deeply-nested child and
    // made `gap` have nothing left to space out). Always pair open/close.
    host.innerHTML = tiers.map(function (t) {
      return '<span class="wui-map-legend-item"><span class="wui-status-dot wui-status-dot-sm ' + t.cls + '"></span>' +
        '<span data-wui-i18n="' + t.key + '">' + t.fallback + '</span></span>';
    }).join("");
    // Breathing room scales with item count instead of a fixed gap — more
    // tiers, more room. wui-gap-x-N only exists for these exact steps
    // (weoc-grid.css skips -7, jumps 6 -> 8, same as the full wui-gap-N
    // scale) — snap down to the nearest real one instead of emitting a
    // class that silently doesn't exist.
    var GAP_X_STEPS = [0, 1, 2, 3, 4, 5, 6, 8];
    var gapStep = 0;
    for (var i = 0; i < GAP_X_STEPS.length; i++) {
      if (GAP_X_STEPS[i] <= tiers.length) gapStep = GAP_X_STEPS[i];
    }
    Array.prototype.slice.call(host.classList).forEach(function (c) {
      if (/^wui-gap-x-\d+$/.test(c)) host.classList.remove(c);
    });
    host.classList.add("wui-gap-x-" + gapStep);
    i18nApply(host);
  };

  /* ---------------------------------------------------------------------------
   * Popover (Display mode) — generic positioning + field binding.
   * The screen-position math is identical across all old views; centralised here.
   * ------------------------------------------------------------------------ */

  function MapPopover(instance) {
    this.instance = instance;
    this.root = instance.root;
    this.pop = el(this.root, "[data-map-popover]");
    this.wrap = el(this.root, "[data-map-wrap]") || this.root;
    this.activeId = null;
    if (this.pop) this._wire();
  }
  MapPopover.prototype._wire = function () {
    var self = this, inst = this.instance;
    var closeBtn = el(this.pop, '[data-map-action="close"]');
    if (closeBtn) inst._on(closeBtn, "click", function () { self.hide(); });

    var locateBtn = el(this.pop, '[data-map-action="locate"]');
    if (locateBtn) inst._on(locateBtn, "click", function () {
      if (!self.activeData) return;
      inst.focus(self.activeData.lat, self.activeData.lon, 13);
    });

    var detailsBtn = el(this.pop, '[data-map-action="details"]');
    if (detailsBtn) inst._on(detailsBtn, "click", function () {
      if (!self.activeData) return;
      var id = self.activeData.id;
      var viewName = inst.opts.detailsView;
      self.hide();
      if (viewName && global.BoardScript && global.BoardScript.OpenView) {
        global.BoardScript.OpenView("", viewName, id, "", "", "", "", "", "");
      } else if (typeof inst.opts.onDetails === "function") {
        inst.opts.onDetails(id, self.activeData);
      }
    });

    // Click anywhere outside the popover / map surface closes it.
    inst._on(document, "click", function (e) {
      if (!e.target.closest("[data-map-popover]") && !e.target.closest(".esri-view-surface")) {
        self.hide();
      }
    });
  };
  MapPopover.prototype.show = function (attrs, graphic) {
    if (!this.pop) return;
    this.activeData = attrs;
    this.activeId = attrs.id;
    this.activeGraphic = graphic;   // kept so we can re-anchor on view change

    // Bind fields: [data-map-field="classification"] <- attrs.classification
    els(this.pop, "[data-map-field]").forEach(function (node) {
      var key = node.getAttribute("data-map-field");
      node.textContent = (attrs[key] != null && attrs[key] !== "") ? attrs[key] : "—";
    });
    // Optional custom decorate hook (accent colour, badges, icon).
    if (typeof this.instance.opts.decoratePopover === "function") {
      this.instance.opts.decoratePopover(this.pop, attrs);
    }

    // Make it visible first so offsetWidth/Height measure the real box.
    this.pop.style.display = "block";
    var pos = anchorXY(this.instance, graphic);
    this._place(pos.x, pos.y);
  };
  // Position the (already-visible) popover at a wrap-relative anchor, clamped
  // inside the wrap. Shared by show() and reposition().
  MapPopover.prototype._place = function (relX, relY) {
    var contW = this.wrap.offsetWidth, contH = this.wrap.offsetHeight;
    var popW = this.pop.offsetWidth || 280, popH = this.pop.offsetHeight || 215, gap = 14;
    var left = relX - popW / 2, top = relY - popH - gap;
    if (left < 8) left = 8;
    if (left + popW > contW - 8) left = contW - popW - 8;
    if (top < 8) top = relY + gap;
    if (top + popH > contH - 8) top = contH - popH - 8;
    this.pop.style.left = left + "px";
    this.pop.style.top = top + "px";
  };
  // Re-anchor to the live marker after the view moves (zoom / pan / rotate /
  // resize / fullscreen), so the popover stays glued to its point.
  MapPopover.prototype.reposition = function () {
    if (!this.pop || this.pop.style.display === "none" || !this.activeGraphic) return;
    var g = this.activeGraphic;
    if (!g.geometry) return;
    var pos = anchorXY(this.instance, g);
    this._place(pos.x, pos.y);
  };
  MapPopover.prototype.hide = function () {
    if (this.pop) this.pop.style.display = "none";
    this.activeId = null;
    this.activeData = null;
    this.activeGraphic = null;
  };

  // Compute popover-anchor coords (relative to the wrap) for a graphic — the
  // mapRect/wrapRect/toScreen dance that every old view repeated verbatim.
  function anchorXY(instance, graphic) {
    var view = instance.view;
    var wrap = el(instance.root, "[data-map-wrap]") || instance.root;
    var mapRect = view.container.getBoundingClientRect();
    var wrapRect = wrap.getBoundingClientRect();
    var sp = view.toScreen(graphic.geometry);
    return { x: (mapRect.left - wrapRect.left) + sp.x, y: (mapRect.top - wrapRect.top) + sp.y };
  }

  /* ---------------------------------------------------------------------------
   * Modes — the only place the three archetypes actually differ.
   * ------------------------------------------------------------------------ */

  var MODES = {

    // DISPLAY: many markers from DOM nodes; click marker -> popover.
    display: {
      onReady: function (inst) {
        inst._popover = new MapPopover(inst);
        MODES.display.refresh(inst);

        inst.view.on("click", function (event) {
          inst.view.hitTest(event).then(function (resp) {
            var hit = resp.results.find(function (r) {
              return r.graphic && r.graphic.attributes && r.graphic.attributes.id != null;
            });
            if (!hit) { if (inst._popover) inst._popover.hide(); return; }
            var attrs = hit.graphic.attributes;
            if (typeof inst.opts.onMarkerClick === "function") {
              inst.opts.onMarkerClick(attrs, hit, inst);
            }
            if (inst._popover) {
              inst._popover.show(attrs, hit.graphic);
            }
          });
        });

        // Keep the popover glued to its marker as the view moves (zoom / pan /
        // rotate / container resize). anchorXY re-projects on every change, so
        // the popover stays anchored instead of only re-anchoring on fullscreen.
        var reanchor = function () { if (inst._popover) inst._popover.reposition(); };
        if (inst.view.watch) { inst.view.watch(["extent", "rotation", "size"], reanchor); }
        if (inst.view.on)    { inst.view.on("resize", reanchor); }
      },
      refresh: function (inst) {
        inst._plot(readPoints(inst));
      }
    },

    // DETAILS: single read-only marker from literal lat/lon (XSL-injected).
    details: {
      onReady: function (inst) {
        var o = inst.opts;
        if (o.lat != null && o.lon != null) {
          inst.setMarker(o.lat, o.lon);
          if (o.emptyEl) o.emptyEl.style.display = "none";
        } else {
          // No coordinates: hide the map surface, show the empty-state element.
          if (inst._viewDiv) inst._viewDiv.style.display = "none";
          if (o.emptyEl) o.emptyEl.style.display = "";
        }
      }
    },

    // INPUT: single editable marker. Click map -> write inputs; type -> move marker.
    input: {
      onReady: function (inst) {
        var o = inst.opts;
        var latInput = el(document, o.latInput);
        var lonInput = el(document, o.lonInput);

        function readInputs() {
          return { lat: num(latInput && latInput.value), lon: num(lonInput && lonInput.value) };
        }
        function syncMarker() {
          var v = readInputs();
          if (v.lat == null || v.lon == null) { inst.layer.removeAll(); return; }
          inst.setMarker(v.lat, v.lon);
          inst.focus(v.lat, v.lon, o.focusZoom);
        }
        inst._syncMarker = syncMarker;

        // Seed from existing values (edit mode or pre-filled from a related record),
        // centring the view on the point so it's visible without a manual pan.
        var seed = readInputs();
        if (seed.lat != null && seed.lon != null) {
          inst.setMarker(seed.lat, seed.lon);
          inst.focus(seed.lat, seed.lon, o.focusZoom);
        }

        // Click-to-drop.
        inst.view.on("click", function (event) {
          if (o.lockedFlag && global[o.lockedFlag]) return;     // e.g. _assigneeMapLocked
          if (inst.root.getAttribute("data-map-locked") === "true") return;
          var lat = event.mapPoint.latitude.toFixed(o.precision);
          var lon = event.mapPoint.longitude.toFixed(o.precision);
          if (latInput) latInput.value = lat;
          if (lonInput) lonInput.value = lon;
          inst.setMarker(parseFloat(lat), parseFloat(lon));
        });

        // Typing in the fields moves the marker (debounced).
        var t;
        function onType() { clearTimeout(t); t = setTimeout(syncMarker, 600); }
        if (latInput) inst._on(latInput, "input", onType);
        if (lonInput) inst._on(lonInput, "input", onType);
      },
      refresh: function (inst) { if (inst._syncMarker) inst._syncMarker(); }
    }
  };

  // Read display-mode points from DOM nodes carrying data-lat/data-lon (+ data-*).
  function readPoints(inst) {
    var o = inst.opts;
    if (Array.isArray(o.points)) return o.points;             // programmatic override
    var nodes = els(document, o.pointsSelector);
    var out = [];
    nodes.forEach(function (node) {
      var d = dataset(node);
      var lat = num(d.lat), lon = num(d.lon);
      if (lat == null || lon == null) return;
      d.lat = lat; d.lon = lon;
      if (d.id == null) d.id = d.record || "";
      out.push(d);
    });
    return out;
  }

  /* ---------------------------------------------------------------------------
   * Option resolution — merge data-* attributes with programmatic opts.
   * ------------------------------------------------------------------------ */

  function resolveOptions(root, userOpts) {
    userOpts = userOpts || {};
    function a(name, dflt) {
      var v = root.getAttribute(name);
      return (v == null || v === "") ? dflt : v;
    }

    var mode = userOpts.mode || a("data-map-mode", "display");
    var viewDiv = userOpts.viewDiv || el(root, "[data-map-view]") ||
                  el(root, ".wui-map-view") || root;

    // style opt may be a builder function OR a registered style name (string).
    var styleName = userOpts.styleName ||
                    (typeof userOpts.style === "string" ? userOpts.style : null) ||
                    a("data-map-style", mode === "display" ? "dot" : "pin");
    var style = (typeof userOpts.style === "function" ? userOpts.style : null) ||
                STYLES[styleName] || STYLES.pin;

    var paletteName = a("data-map-palette");
    var palette = userOpts.palette || (paletteName && PALETTES[paletteName]) || null;

    var center = userOpts.center || parseCenter(a("data-map-center")) || DEFAULT_CENTER;
    var zoom = userOpts.zoom != null ? userOpts.zoom : parseFloat(a("data-map-zoom", DEFAULT_ZOOM));
    var focusZoom = userOpts.focusZoom != null ? userOpts.focusZoom : parseFloat(a("data-map-focus-zoom", mode === "input" ? 13 : 15));

    var o = {
      mode: MODES[mode] ? mode : "display",
      viewDiv: viewDiv,
      basemapIndex: resolveBasemapStart(root),
      center: center,
      zoom: isNaN(zoom) ? DEFAULT_ZOOM : zoom,
      focusZoom: isNaN(focusZoom) ? 15 : focusZoom,

      style: style,
      styleName: styleName,
      palette: palette,
      color: userOpts.color || parseColor(a("data-map-color")),
      outline: userOpts.outline || parseColor(a("data-map-outline")),
      size: userOpts.size || a("data-map-size"),
      colorField: userOpts.colorField || a("data-map-color-field", "status"),
      fit: userOpts.fit != null ? userOpts.fit : (a("data-map-fit") === "true"),

      // display
      pointsSelector: userOpts.pointsSelector || a("data-map-points", "[data-lat]"),
      points: userOpts.points || null,
      detailsView: userOpts.detailsView || a("data-map-details-view"),
      onMarkerClick: userOpts.onMarkerClick,
      decoratePopover: userOpts.decoratePopover,
      onDetails: userOpts.onDetails,

      // details
      lat: userOpts.lat != null ? userOpts.lat : num(a("data-map-lat")),
      lon: userOpts.lon != null ? userOpts.lon : num(a("data-map-lon")),
      // emptyEl accepts an element or a selector string (opts), or data-map-empty (attr).
      emptyEl: (typeof userOpts.emptyEl === "string" ? el(document, userOpts.emptyEl) : userOpts.emptyEl) ||
               (a("data-map-empty") ? el(document, a("data-map-empty")) : null),

      // input
      latInput: userOpts.latInput || a("data-map-lat-input", 'input[name="Latitude"]'),
      lonInput: userOpts.lonInput || a("data-map-lon-input", 'input[name="Longitude"]'),
      precision: userOpts.precision != null ? userOpts.precision : parseInt(a("data-map-precision", "6"), 10),
      lockedFlag: userOpts.lockedFlag || a("data-map-locked-flag"),

      // badge style config
      tierField: userOpts.tierField || a("data-map-tier-field", "severity"),
      iconField: userOpts.iconField || a("data-map-icon-field", "classification"),
      iconBase: userOpts.iconBase || a("data-map-icon-base"),
      iconSet: userOpts.iconSet || null,
      iconFallback: userOpts.iconFallback || a("data-map-icon-fallback"),

      // optional companion widgets — generated, not markup (see header)
      weather: userOpts.weather || null,
      legend: userOpts.legend != null ? userOpts.legend : (a("data-map-legend") === "true" ? true : null)
    };
    return o;
  }

  /* ---------------------------------------------------------------------------
   * Public factory
   * ------------------------------------------------------------------------ */

  var WeocMap = {
    BASEMAPS: BASEMAPS,
    STYLES: STYLES,
    PALETTES: PALETTES,

    registerStyle: function (name, fn) { STYLES[name] = fn; return this; },
    registerPalette: function (name, map) { PALETTES[name] = map; return this; },

    create: function (rootOrSelector, opts) {
      var root = (typeof rootOrSelector === "string")
        ? el(document, rootOrSelector) : rootOrSelector;
      if (!root) { console.warn("[WeocMap] root not found:", rootOrSelector); return null; }
      var resolved = resolveOptions(root, opts);
      var inst = new WeocMapInstance(root, resolved);
      root.__weocMap = inst;
      return inst;
    },

    // Boot every [data-wui-map] in scope that hasn't been booted yet.
    // Skips [data-map-manual] — those are created by hand (to pass function
    // hooks like decoratePopover / onDetails that can't live in attributes).
    autoInit: function (scope) {
      return els(scope || document, "[data-wui-map]").map(function (root) {
        if (root.__weocMap) return root.__weocMap;
        if (root.hasAttribute("data-map-manual")) return null;
        return WeocMap.create(root);
      }).filter(Boolean);
    }
  };

  // Auto-init on DOM ready. Boards that need to register palettes/styles/icon
  // sets first can either do so before this fires, or set data-map-manual on the
  // root and call WeocMap.create(...) themselves.
  function boot() {
    WeocMap.autoInit(document);
  }
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", boot);
  } else {
    boot();
  }

  global.WeocMap = WeocMap;

})(window);
